require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb
Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*.rb
RSpec/ContextWording:
  Prefixes:
    - and
    - but
    - when
    - with
    - without
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
