name: Test
on:
  - push
  - pull_request
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@main
      - name: Build image and run tests
        run: docker run --rm $(docker build -f spec/Dockerfile -q .)